---
- name: Add apt repository
  include_tasks: add_apt_repository.yml

- name: Update apt repositories
  apt:
    update_cache: yes
  when: not (ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '10' or ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version == '18')

- name: Install MariaDB
  apt:
    name:
      - mariadb-server

- name: Install python-pymysql when python 2.*
  apt:
    name:
      - python-pymysql
  when: ansible_python_version is match("2\..*")

- name: Install python3-pymysql when python 3.*
  apt:
    name:
      - python3-pymysql
  when: ansible_python_version is match("3\..*")

- name: Update MariaDB password for root account
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_password: "{{ mariadb_root_password }}"
    host: "localhost"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
